import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase.js';
const cards=[['submitted','New requests','Waiting for the office','Help & Support'],['reviewing','Being reviewed','Requests in progress','Help & Support'],['needs_information','Awaiting alumni reply','More information requested','Help & Support'],['completed','Completed requests','Marked complete by the office','Help & Support'],['groups','Batch groups','Groups and membership management','Community & Requests'],['announcements','Announcements','General and batch announcements','Community & Requests']];
export default function CommunityOverview({onNavigate}){
 const [counts,setCounts]=useState({}),[recent,setRecent]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState(null),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true,running=false;
 async function load(){if(running||document.hidden)return;running=true;if(active)setBusy(true);const count=async(table,configure=q=>q)=>{const {count,error}=await configure(supabase.from(table).select('id',{count:'exact',head:true}));if(error)throw error;return count||0;};
 try{const checks=await Promise.allSettled([
 ...['submitted','reviewing','needs_information','completed'].map(status=>count('alumni_service_items',q=>q.eq('kind','request').eq('status',status))),count('alumni_spaces'),Promise.all([count('alumni_service_items',q=>q.eq('kind','announcement')),count('batch_entries',q=>q.eq('kind','announcement'))]).then(values=>values.reduce((a,b)=>a+b,0)),
 (async()=>{const {data,error}=await supabase.from('alumni_service_items').select('id,title,category,status,created_at').eq('kind','request').order('created_at',{ascending:false}).limit(4);if(error)throw error;return data;})()
 ]);if(!active)return;setCounts(Object.fromEntries(cards.map(([key],i)=>[key,checks[i].status==='fulfilled'?checks[i].value:null])));setRecent(checks[6].status==='fulfilled'?checks[6].value:[]);setError(checks.some(c=>c.status==='rejected')?'Some community data could not be loaded. Check your session and try Refresh.':'');setUpdated(new Date());}catch(e){if(active)setError(e.message);}finally{running=false;if(active)setBusy(false);}}
 load();const timer=setInterval(load,15000);window.addEventListener('support-requests-changed',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('support-requests-changed',load);};},[revision]);
 return <section className="admin-community-overview" aria-labelledby="community-overview-title"><header className="panel-heading"><div><p>Support &amp; alumni community</p><h2 id="community-overview-title">Stay on top of alumni requests</h2><span>Updates every 15 seconds while this dashboard is visible.</span></div><button type="button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>{busy?'Updating...':'Refresh'}</button></header>{error&&<p className="admin-access-error" role="alert">{error}</p>}<div className="community-dashboard-metrics">{cards.map(([key,label,note,page])=><button type="button" key={key} onClick={()=>onNavigate(page)} className={key==='submitted'&&counts[key]>0?'needs-attention':''}><span>{label}</span><strong>{counts[key]===undefined?'...':counts[key]===null?'Unavailable':counts[key].toLocaleString()}</strong><small>{note}</small></button>)}</div><div className="community-dashboard-bottom"><article className="admin-panel"><header><h3>Latest support requests</h3><button type="button" onClick={()=>onNavigate('Help & Support')}>View all requests</button></header>{recent.length?recent.map(r=><button type="button" className="dashboard-support-request" key={r.id} onClick={()=>onNavigate('Help & Support')}><span><strong>{r.title}</strong><small>{r.category} &middot; {new Date(r.created_at).toLocaleDateString()}</small></span><b className={`support-status-${r.status}`}>{cards.find(c=>c[0]===r.status)?.[1]||r.status}</b></button>):<p className="demographic-empty">{busy?'Loading requests...':error?'Requests are unavailable right now.':'No support requests yet. New alumni requests will appear here.'}</p>}</article><article className="admin-panel community-dashboard-shortcuts"><h3>Manage the new features</h3><button type="button" onClick={()=>onNavigate('Help & Support')}><strong>Help &amp; Support <span aria-hidden="true">&#8594;</span></strong><small>Read requests, reply to alumni and update their status.</small></button><button type="button" onClick={()=>onNavigate('Community & Requests')}><strong>Groups &amp; announcements <span aria-hidden="true">&#8594;</span></strong><small>Manage batch groups and publish alumni updates.</small></button><p>Chat nicknames, covers, shared photos and pinned messages are managed inside each conversation.</p></article></div>{updated&&<p className="community-dashboard-updated">Last checked at {updated.toLocaleTimeString()}</p>}</section>;
}
