import {useEffect,useState} from 'react';
import {adminApi} from '../../lib/adminApi.js';

export default function ModerationQueue(){
  const[reports,setReports]=useState([]),[status,setStatus]=useState('open'),[notes,setNotes]=useState({}),[message,setMessage]=useState('');
  async function load(){try{const r=await adminApi(`/api/admin/moderation/reports?status=${status}`);setReports(r.reports||[])}catch(e){setMessage(e.message)}}
  useEffect(()=>{load()},[status]);
  async function decide(report,next,action){const reason=(notes[report.id]||'').trim();if(!reason)return setMessage('Add a reason before recording a moderation decision.');try{await adminApi(`/api/admin/moderation/reports/${report.id}`,{method:'PATCH',body:JSON.stringify({status:next,action,reason})});setMessage('Moderation decision recorded and applied to the content.');load()}catch(e){setMessage(e.message)}}
  return <section className="admin-panel connected-moderation"><header><div><p>Safety queue</p><h2>Content reports</h2><span>Review the reported content, its author, and the reporter’s context before deciding.</span></div><nav>{['open','under_review','resolved','dismissed','all'].map(x=><button className={status===x?'active':''} onClick={()=>setStatus(x)} key={x}>{x.replace('_',' ')}</button>)}</nav></header>{message&&<p className="admin-resource-message">{message}</p>}{reports.length?<div className="moderation-report-list">{reports.map(report=><article key={report.id}><header><span className={`report-reason ${report.reason}`}>{report.reason}</span><time>{new Date(report.created_at).toLocaleString()}</time></header><h3>{report.target_type.replace('_',' ')} · {report.target?.author_name||'Content unavailable'}</h3><blockquote>{report.target?.content||'The reported content is no longer available.'}</blockquote><p>{report.details||'No additional reporter details.'}</p><small>Reported by {[report.profiles?.first_name,report.profiles?.last_name].filter(Boolean).join(' ')||report.profiles?.email||'Member'} · Status: {report.target?.moderation_status||'unknown'}</small>{['open','under_review'].includes(report.status)&&<><textarea value={notes[report.id]||''} onChange={e=>setNotes({...notes,[report.id]:e.target.value})} placeholder="Required decision reason or internal note"/><footer><button onClick={()=>decide(report,'dismissed','keep')}>Keep content</button><button onClick={()=>decide(report,'under_review','escalate')}>Escalate / assign</button><button className="warn" onClick={()=>decide(report,'resolved','warn')}>Warn author</button><button className="danger" onClick={()=>decide(report,'resolved','hide')}>Hide content</button><button className="danger" onClick={()=>decide(report,'resolved','remove')}>Move to Trash</button></footer></>}</article>)}</div>:<div className="content-empty"><strong>No {status==='all'?'':status.replace('_',' ')} reports</strong><span>The moderation queue is clear.</span></div>}</section>
}
