import { useEffect, useState } from 'react';
import { adminApi } from '../../lib/adminApi.js';

export default function SystemSettings() {
  const [tab, setTab] = useState('Configuration');
  const [settings, setSettings] = useState(null);
  const [logs, setLogs] = useState([]);
  const [message, setMessage] = useState('');
  async function load() { try { const [a,b] = await Promise.all([adminApi('/api/admin/settings'),adminApi('/api/admin/audit-logs')]); setSettings(a.settings); setLogs(b.logs || []); setMessage(''); } catch (error) { setMessage(error.message); } }
  useEffect(() => { load(); }, []);
  async function save(event) { event.preventDefault(); try { const result = await adminApi('/api/admin/settings',{method:'PUT',body:JSON.stringify(settings)}); setSettings(result.settings); setMessage('Settings saved and recorded in the audit log.'); } catch(error) { setMessage(error.message); } }
  return <div className="settings-page"><header className="admin-page-header settings-header"><div><p>Connected administration</p><h1>System Settings</h1><span>Configuration changes are saved to Supabase and audited.</span></div><button onClick={load}>↻ Refresh</button></header>{message && <p className="admin-resource-message">{message}</p>}<nav className="settings-tabs">{['Configuration','Activity Logs','Recommendations'].map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav>
    {tab==='Configuration' && (settings ? <form className="settings-grid" onSubmit={save}><article className="admin-panel setting-card school-info-card"><header><h2>School information</h2></header><label>Institution name<input value={settings.institution_name||''} onChange={e=>setSettings({...settings,institution_name:e.target.value})}/></label><label>Contact email<input type="email" value={settings.contact_email||''} onChange={e=>setSettings({...settings,contact_email:e.target.value})}/></label><button className="settings-submit">Save changes</button></article><article className="admin-panel setting-card registration-card"><header><h2>Registration</h2></header><label className="setting-toggle"><span><strong>Allow open signups</strong><p>New users can create accounts.</p></span><input type="checkbox" checked={settings.allow_open_signups} onChange={e=>setSettings({...settings,allow_open_signups:e.target.checked})}/></label><label className="setting-toggle"><span><strong>Verify domain</strong><p>Require an approved email domain.</p></span><input type="checkbox" checked={settings.verify_domain} onChange={e=>setSettings({...settings,verify_domain:e.target.checked})}/></label></article></form> : <section className="admin-panel admin-live-loading">Loading settings…</section>)}
    {tab==='Activity Logs' && <section className="admin-panel admin-audit-table">{logs.length?logs.map(log=><article key={log.id}><strong>{log.action}</strong><span>{log.target_type}{log.target_id?` · ${log.target_id}`:''}</span><time>{new Date(log.created_at).toLocaleString()}</time></article>):<p>No administrative activity recorded.</p>}</section>}
    {tab==='Recommendations' && <section className="admin-panel admin-recommendations"><h2>Recommended next improvements</h2><ol><li>Enable scheduled database backups and test restoration quarterly.</li><li>Add user reporting for posts and messages; reveal only specifically reported content.</li><li>Add retention rules and malware scanning for chat attachments.</li><li>Connect email templates to verification decisions and event reminders.</li><li>Add rate limits for posts, messages, uploads, and GIF searches.</li></ol></section>}
  </div>;
}
