import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase.js';
import './AlumniProfilePage.css';
import './ProfilePageEnhancements.css';
import './ProfileMediaEditor.css';

const EMOJIS=['😀','🎉','❤️','🙏','👏','🌟'];
const nameOf=(p)=>[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Alumni member';

export default function AlumniProfilePage({user,profile,onProfileChange}){
  const [details,setDetails]=useState(null),[posts,setPosts]=useState([]),[friends,setFriends]=useState([]),[tab,setTab]=useState('posts');
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[composer,setComposer]=useState(false),[content,setContent]=useState(''),[photo,setPhoto]=useState(null),[publishing,setPublishing]=useState(false),[expanded,setExpanded]=useState([]),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false);
  const [edit,setEdit]=useState({first_name:'',last_name:'',degree:'',course:'',department:'',graduation_year:'',batch_name:'',honors:''});
  const [avatarFile,setAvatarFile]=useState(null),[coverFile,setCoverFile]=useState(null),[removeAvatar,setRemoveAvatar]=useState(false),[removeCover,setRemoveCover]=useState(false);
  const photoRef=useRef(null);

  async function load(){
    setLoading(true);setError('');
    const [detailResult,postResult,connectionResult,directoryResult]=await Promise.all([
      supabase.rpc('get_public_alumni_profile',{p_profile_id:user.id}).maybeSingle(),
      supabase.from('feed_posts').select('id,user_id,author_name,author_avatar_url,content,media_path,gif_url,created_at,feed_reactions(user_id,reaction),feed_comments(id,user_id,author_name,content,media_path,gif_url,parent_comment_id,created_at)').eq('user_id',user.id).eq('moderation_status','published').is('deleted_at',null).order('created_at',{ascending:false}),
      supabase.from('alumni_connections').select('user_low,user_high,status').eq('status','accepted').or(`user_low.eq.${user.id},user_high.eq.${user.id}`),
      supabase.rpc('list_chat_profiles'),
    ]);
    if(detailResult.error)setError(detailResult.error.message);
    setDetails(detailResult.data);setPosts(postResult.data||[]);
    const ids=new Set((connectionResult.data||[]).map(row=>row.user_low===user.id?row.user_high:row.user_low));
    setFriends((directoryResult.data||[]).filter(person=>ids.has(person.id)));setLoading(false);
  }
  useEffect(()=>{load()},[user.id]);
  const display={...profile,...details},name=nameOf(display),initials=name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
  const photos=useMemo(()=>posts.filter(post=>post.media_path||post.gif_url),[posts]);
  const avatarPreview=useMemo(()=>avatarFile?URL.createObjectURL(avatarFile):removeAvatar?'':display.avatar_url,[avatarFile,removeAvatar,display.avatar_url]);
  const coverPreview=useMemo(()=>coverFile?URL.createObjectURL(coverFile):removeCover?'':display.cover_url,[coverFile,removeCover,display.cover_url]);
  useEffect(()=>()=>{if(avatarPreview?.startsWith('blob:'))URL.revokeObjectURL(avatarPreview)},[avatarPreview]);
  useEffect(()=>()=>{if(coverPreview?.startsWith('blob:'))URL.revokeObjectURL(coverPreview)},[coverPreview]);

  function openEditor(){setEdit({first_name:display.first_name||'',last_name:display.last_name||'',degree:display.degree||'',course:display.course||'',department:display.department||'',graduation_year:display.graduation_year||'',batch_name:display.batch_name||'',honors:display.honors||''});setAvatarFile(null);setCoverFile(null);setRemoveAvatar(false);setRemoveCover(false);setEditing(true)}
  async function saveProfile(event){
    event.preventDefault();setSaving(true);setError('');let avatarPath=null,coverPath=null;
    const validTypes=['image/jpeg','image/png','image/webp'];
    if(avatarFile&&(!validTypes.includes(avatarFile.type)||avatarFile.size>2*1024*1024)){setError('Profile pictures must be JPG, PNG, or WebP and no larger than 2 MB.');setSaving(false);return}
    if(coverFile&&(!validTypes.includes(coverFile.type)||coverFile.size>5*1024*1024)){setError('Cover photos must be JPG, PNG, or WebP and no larger than 5 MB.');setSaving(false);return}
    let avatarUrl=removeAvatar?null:display.avatar_url||null,coverUrl=removeCover?null:display.cover_url||null;
    try{
      if(avatarFile){avatarPath=`${user.id}/${crypto.randomUUID()}.${avatarFile.name.split('.').pop().toLowerCase()}`;const upload=await supabase.storage.from('profile-avatars').upload(avatarPath,avatarFile,{contentType:avatarFile.type});if(upload.error)throw upload.error;avatarUrl=supabase.storage.from('profile-avatars').getPublicUrl(avatarPath).data.publicUrl}
      if(coverFile){coverPath=`${user.id}/covers/${crypto.randomUUID()}.${coverFile.name.split('.').pop().toLowerCase()}`;const upload=await supabase.storage.from('profile-avatars').upload(coverPath,coverFile,{contentType:coverFile.type});if(upload.error)throw upload.error;coverUrl=supabase.storage.from('profile-avatars').getPublicUrl(coverPath).data.publicUrl}
    }catch(problem){if(avatarPath)await supabase.storage.from('profile-avatars').remove([avatarPath]);if(coverPath)await supabase.storage.from('profile-avatars').remove([coverPath]);setError(problem.message);setSaving(false);return}
    const profileResult=await supabase.rpc('save_own_alumni_profile',{p_first_name:edit.first_name.trim(),p_last_name:edit.last_name.trim(),p_avatar_url:avatarUrl,p_cover_url:coverUrl,p_degree:edit.degree.trim()||null,p_course:edit.course.trim()||null,p_department:edit.department.trim()||null,p_graduation_year:edit.graduation_year?Number(edit.graduation_year):null,p_batch_name:edit.batch_name.trim()||null,p_honors:edit.honors.trim()||null});
    if(profileResult.error){if(avatarPath)await supabase.storage.from('profile-avatars').remove([avatarPath]);if(coverPath)await supabase.storage.from('profile-avatars').remove([coverPath]);setError(profileResult.error.message);setSaving(false);return}
    const storedPath=url=>decodeURIComponent(url?.split('/profile-avatars/')[1]?.split('?')[0]||'');
    const obsolete=[];if(avatarPath||removeAvatar)obsolete.push(storedPath(display.avatar_url));if(coverPath||removeCover)obsolete.push(storedPath(display.cover_url));
    const ownedObsolete=obsolete.filter(path=>path.startsWith(`${user.id}/`)&&path!==avatarPath&&path!==coverPath);if(ownedObsolete.length)await supabase.storage.from('profile-avatars').remove(ownedObsolete);
    onProfileChange?.(profileResult.data.profile);setEditing(false);setSaving(false);await load();setError('Profile saved successfully.');
  }
  async function publish(event){
    event.preventDefault();if(!content.trim()&&!photo)return;setPublishing(true);setError('');let mediaPath=null;
    try{if(photo){if(!['image/jpeg','image/png','image/webp'].includes(photo.type)||photo.size>10*1024*1024)throw new Error('Use a JPG, PNG, or WebP photo no larger than 10 MB.');mediaPath=`${user.id}/${crypto.randomUUID()}.${photo.name.split('.').pop().toLowerCase()}`;const upload=await supabase.storage.from('feed-media').upload(mediaPath,photo,{contentType:photo.type});if(upload.error)throw upload.error}
      const result=await supabase.from('feed_posts').insert({user_id:user.id,author_name:name,author_avatar_url:display.avatar_url||null,content:content.trim(),media_path:mediaPath}).select().single();if(result.error)throw result.error;setContent('');setPhoto(null);if(photoRef.current)photoRef.current.value='';setComposer(false);await load();
    }catch(problem){if(mediaPath)await supabase.storage.from('feed-media').remove([mediaPath]);setError(problem.message)}finally{setPublishing(false)}
  }

  return <section className="alumni-profile-page"><div className="profile-cover"><div className="profile-cover-pattern" style={display.cover_url?{backgroundImage:`url(${display.cover_url})`}:undefined}/><div className="profile-identity"><div className="profile-page-avatar">{display.avatar_url?<img src={display.avatar_url} alt={`${name}'s profile`}/>:initials}</div><div><p>Verified alumni profile</p><h1>{name}</h1><span>{[display.course,display.graduation_year&&`Class of ${display.graduation_year}`].filter(Boolean).join(' · ')||'Notre Dame of Dadiangas University'}</span></div><button onClick={openEditor}>Edit profile</button></div></div>
  <nav className="profile-tabs" aria-label="Profile sections">{[['posts','Posts'],['about','About'],['friends',`Friends ${details?.friend_count||0}`],['photos',`Photos ${photos.length}`]].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {error&&<p className="profile-page-message" role="alert">{error}</p>}{loading?<p className="profile-page-message">Loading your profile…</p>:<div className="profile-page-grid"><aside><section className="profile-intro"><h2>Intro</h2><dl>{[['Degree',display.degree],['Course',display.course],['Department',display.department],['Graduated',display.graduation_year&&`Class of ${display.graduation_year}`],['Batch',display.batch_name],['Honors',display.honors],['Position',display.job_title],['Organization',display.organization]].filter(([,v])=>v).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button onClick={openEditor}>Edit details</button></section><section className="profile-friend-preview"><header><h2>Friends</h2><button onClick={()=>setTab('friends')}>See all</button></header><p>{details?.friend_count||0} friends · {details?.mutual_count||0} mutual</p><div>{friends.slice(0,6).map(friend=><article key={friend.id}>{friend.avatar_url?<img src={friend.avatar_url} alt=""/>:<b>{nameOf(friend).slice(0,1)}</b>}<span>{nameOf(friend)}</span></article>)}</div></section></aside>
  <main className="profile-tab-content">{tab==='posts'&&<><header><h2>Posts</h2><button onClick={()=>setComposer(open=>!open)}>{composer?'Close composer':'Create post'}</button></header>{composer&&<form className="profile-composer" onSubmit={publish}><textarea autoFocus maxLength="2000" value={content} onChange={e=>setContent(e.target.value)} placeholder="What would you like to share?"/><div className="profile-composer-emojis">{EMOJIS.map(emoji=><button type="button" key={emoji} onClick={()=>setContent(value=>value+emoji)}>{emoji}</button>)}</div><label>Add photo<input ref={photoRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label>{photo&&<small>{photo.name}</small>}<button disabled={publishing||(!content.trim()&&!photo)}>{publishing?'Publishing…':'Publish post'}</button></form>}{posts.length?posts.map(post=>{const isOpen=expanded.includes(post.id);const reactions=post.feed_reactions||[],comments=post.feed_comments||[];return <article className="profile-post" key={post.id}><header><div className="profile-post-avatar">{display.avatar_url?<img src={display.avatar_url} alt=""/>:initials}</div><div><strong>{name}</strong><time>{new Date(post.created_at).toLocaleString()}</time></div></header>{post.content&&<p>{post.content}</p>}{post.media_path&&<img src={supabase.storage.from('feed-media').getPublicUrl(post.media_path).data.publicUrl} alt="Post attachment"/>}{post.gif_url&&<img src={post.gif_url} alt="Posted GIF"/>}<button className="profile-post-stats" onClick={()=>setExpanded(current=>current.includes(post.id)?current.filter(id=>id!==post.id):[...current,post.id])}>{reactions.length} reactions · {comments.length} comments</button>{isOpen&&<div className="profile-post-activity"><section><h3>Reactions</h3>{reactions.length?<p>{['like','celebrate','support'].map(type=>`${reactions.filter(r=>r.reaction===type).length} ${type}`).join(' · ')}</p>:<p>No reactions yet.</p>}</section><section><h3>Comments</h3>{comments.length?<ul>{comments.map(comment=><li key={comment.id}><strong>{comment.author_name}</strong><p>{comment.content||'Shared an attachment'}</p><time>{new Date(comment.created_at).toLocaleString()}</time></li>)}</ul>:<p>No comments yet.</p>}</section></div>}</article>}):<div className="profile-empty"><h3>No posts yet</h3><p>Your community updates will appear here.</p><button onClick={()=>setComposer(true)}>Write your first post</button></div>}</>}
  {tab==='about'&&<section className="profile-about"><h2>About</h2><dl>{Object.entries({Degree:display.degree,'Course / program':display.course,Department:display.department,'Graduation year':display.graduation_year,Batch:display.batch_name,Honors:display.honors,Position:display.job_title,Organization:display.organization}).filter(([,v])=>v).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button onClick={openEditor}>Edit details</button></section>}
  {tab==='friends'&&<section><header><h2>Friends</h2></header><div className="profile-friends-grid">{friends.length?friends.map(friend=><article key={friend.id}>{friend.avatar_url?<img src={friend.avatar_url} alt=""/>:<b>{nameOf(friend).slice(0,1)}</b>}<strong>{nameOf(friend)}</strong><span>{[friend.course,friend.graduation_year&&`Class of ${friend.graduation_year}`].filter(Boolean).join(' · ')||'NDDU Alumni'}</span></article>):<div className="profile-empty"><h3>No friends yet</h3></div>}</div></section>}
  {tab==='photos'&&<section><header><h2>Photos</h2></header><div className="profile-photos">{photos.length?photos.map(post=><img key={post.id} src={post.gif_url||supabase.storage.from('feed-media').getPublicUrl(post.media_path).data.publicUrl} alt="Shared by this alumnus"/>):<div className="profile-empty"><h3>No photos yet</h3></div>}</div></section>}</main></div>}
  {editing&&<div className="profile-edit-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(false)}><form className="profile-edit-dialog" onSubmit={saveProfile}><header><h2>Edit alumni profile</h2><button type="button" onClick={()=>setEditing(false)} aria-label="Close">×</button></header><div className="profile-media-editor"><div className="profile-cover-editor" style={coverPreview?{backgroundImage:`url(${coverPreview})`}:undefined}><span>Cover photo</span><label>Choose cover<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{setCoverFile(event.target.files?.[0]||null);setRemoveCover(false)}}/></label>{coverPreview&&<button type="button" onClick={()=>{setCoverFile(null);setRemoveCover(true)}}>Remove</button>}</div><div className="profile-avatar-editor">{avatarPreview?<img src={avatarPreview} alt="Profile picture preview"/>:<span>{initials}</span>}<div><strong>Profile picture</strong><small>JPG, PNG, or WebP · maximum 2 MB</small><label>Choose picture<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{setAvatarFile(event.target.files?.[0]||null);setRemoveAvatar(false)}}/></label>{avatarPreview&&<button type="button" onClick={()=>{setAvatarFile(null);setRemoveAvatar(true)}}>Remove</button>}</div></div></div><div className="profile-edit-grid">{[['first_name','First name'],['last_name','Last name'],['degree','Degree'],['course','Course / program'],['department','Department'],['graduation_year','Graduation year'],['batch_name','Batch name'],['honors','Honors']].map(([key,label])=><label key={key}>{label}<input type={key==='graduation_year'?'number':'text'} min={key==='graduation_year'?'1900':undefined} max={key==='graduation_year'?new Date().getFullYear():undefined} maxLength="180" required={key==='first_name'||key==='last_name'} value={edit[key]} onChange={e=>setEdit(current=>({...current,[key]:e.target.value}))}/></label>)}</div><footer><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button disabled={saving}>{saving?'Saving…':'Save changes'}</button></footer></form></div>}</section>;
}
