import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase.js';
import BatchConversation, { batchResult, memberName } from './BatchConversation.jsx';
import './BatchGroups.css';

function BatchPhoto({group}){return group.photo_url?<img className="batch-photo" src={group.photo_url} alt={`${group.name} batch photo`}/>:<span className="batch-photo batch-initials" aria-hidden="true">{group.batch_year||group.name.slice(0,2).toUpperCase()}</span>;}

export default function BatchGroups({user,admin=false,onBackToFeed,onBackToDirectory,onOpenChat,onMessage,onOpenHelp,initialGroupId,initialAnnouncementId}){
 const[groups,setGroups]=useState([]),[selected,setSelected]=useState(initialGroupId||null),[tab,setTab]=useState('announcement');
 const[members,setMembers]=useState([]),[directory,setDirectory]=useState([]),[manager,setManager]=useState(false);
 const[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[editing,setEditing]=useState(false);
 const group=groups.find(g=>g.id===selected);
 const[memberQuery,setMemberQuery]=useState('');
 const visibleMembers=members.filter(p=>memberName(p).toLowerCase().includes(memberQuery.trim().toLowerCase()));
 async function messageMember(id){
  setBusy(true);setError('');
  try{const allowed=await batchResult(supabase.rpc('list_chat_profiles'));const person=allowed.find(p=>p.id===id);if(!person)throw new Error('Messaging is not available for this member.');onMessage?.(person);}
  catch(e){setError(e.message);}finally{setBusy(false);}
 }
 useEffect(()=>{let active=true;setGroups([]);setManager(false);setLoading(true);setError('');if(!user){setLoading(false);return;}
  Promise.all([batchResult(supabase.rpc('list_batch_groups')),batchResult(supabase.rpc('community_manager'))]).then(([rows,allowed])=>{if(active){setGroups(rows);setManager(allowed===true);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};
 },[user?.id,revision]);
 useEffect(()=>{let active=true;setMembers([]);if(group&&(group.joined||manager))batchResult(supabase.rpc('list_batch_members',{p_space:group.id})).then(rows=>{if(active)setMembers(rows);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[group?.id,group?.joined,manager,revision]);
 useEffect(()=>{let active=true;if(manager&&editing)batchResult(supabase.rpc('list_alumni_directory')).then(rows=>{if(active)setDirectory(rows);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[manager,editing]);
 async function membership(){if(busy)return;if(group.joined&&!window.confirm('Leave this batch? You will also lose access to its group chat.'))return;setBusy(true);setError('');try{await batchResult(group.joined?supabase.from('alumni_space_members').delete().eq('space_id',group.id).eq('user_id',user.id):supabase.from('alumni_space_members').insert({space_id:group.id,user_id:user.id}));setNotice(group.joined?'You left the batch and its group chat.':'You joined the batch. Its group chat is now available in Chats.');setRevision(n=>n+1);window.dispatchEvent(new Event('batch-membership-changed'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();setBusy(true);setError('');const fields=new FormData(e.currentTarget);let uploaded=null;try{
  let photo=group?.photo_url||null;const file=fields.get('photo');if(file?.size){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Choose a JPG, PNG, or WebP photo up to 5 MB.');uploaded=`${user.id}/${crypto.randomUUID()}`;await batchResult(supabase.storage.from('batch-photos').upload(uploaded,file,{contentType:file.type}));photo=supabase.storage.from('batch-photos').getPublicUrl(uploaded).data.publicUrl;}
  const payload={name:fields.get('name').trim(),description:fields.get('description').trim(),batch_year:Number(fields.get('year')),president_id:fields.get('president')||null,photo_url:photo,rules:fields.get('rules').trim()};
  await batchResult(group?supabase.from('alumni_spaces').update(payload).eq('id',group.id):supabase.from('alumni_spaces').insert(payload));setEditing(false);setNotice('Batch details saved.');setRevision(n=>n+1);
 }catch(e){if(uploaded)await supabase.storage.from('batch-photos').remove([uploaded]);setError(e.message);}finally{setBusy(false);}}
 return <section className="batch-page">
  {onBackToFeed&&!selected&&<button onClick={onBackToFeed}>← Back to community feed</button>}
  {onBackToDirectory&&!selected&&<button onClick={onBackToDirectory}>← Back to alumni directory</button>}
  {selected&&<button onClick={()=>{setSelected(null);setEditing(false);setNotice('');}}>← All batch groups</button>}
  <header className="batch-hero"><p>NDDU ALUMNI COMMUNITY</p><h1>{group?group.name:'Alumni batch groups'}</h1><p>{group?'Your batch’s place to reconnect, share updates, and help each other.':'Find your batch community. Read batch announcements, find classmates, and open your group conversation in Chats.'}</p></header>
  {error&&<p role="alert" className="batch-feedback">{error} <button onClick={()=>setRevision(n=>n+1)}>Retry</button></p>}{notice&&<p role="status" className="batch-feedback">{notice}</p>}
  {!user?<p>Please sign in with a verified alumni account to view batch communities.</p>:<>
  {!group&&!selected&&<div className="batch-toolbar"><label>Find a batch<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Batch name, year, or president"/></label>{admin&&manager&&<button className="batch-primary" onClick={()=>setEditing(v=>!v)}>{editing?'Cancel':'Create batch group'}</button>}</div>}
  {editing&&manager&&<form className="batch-card batch-edit" onSubmit={save} key={selected||'new'}><h2>{group?'Edit batch details':'Create batch group'}</h2><label>Batch name<input name="name" defaultValue={group?.name||''} required minLength={3} maxLength={100} placeholder="Batch 2007 — Minakawa"/></label><label>Batch year<input name="year" type="number" min={1953} max={new Date().getFullYear()} defaultValue={group?.batch_year||''} required/></label><label>Batch president<select name="president" defaultValue={group?.president_id||''}><option value="">Not assigned yet</option>{group?.president_id&&!directory.some(p=>p.id===group.president_id)&&<option value={group.president_id}>{group.president_name||'Current president'}</option>}{directory.map(p=><option key={p.id} value={p.id}>{memberName(p)}{p.graduation_year?` · ${p.graduation_year}`:''}</option>)}</select></label><label>Batch photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/><small>Public batch photo, up to 5 MB. Use a photo you have permission to share.</small></label><label>About this batch<textarea name="description" maxLength={1000} defaultValue={group?.description||''}/></label><label>Group rules<textarea name="rules" maxLength={2000} defaultValue={group?.rules||'Be respectful. Protect personal information. Keep discussions relevant to the batch.'}/></label><button className="batch-primary" disabled={busy}>{busy?'Saving…':'Save batch'}</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></form>}
  {loading?<p role="status">Loading batch groups…</p>:!selected?<div className="batch-grid">{groups.filter(g=>`${g.name} ${g.batch_year||''} ${g.president_name||''}`.toLowerCase().includes(query.toLowerCase())).map(g=><button className="batch-card batch-directory-card" key={g.id} onClick={()=>{setSelected(g.id);setTab('announcement');setMemberQuery('');setEditing(false);setNotice('');}}><BatchPhoto group={g}/><h2>{g.name}</h2><p>{g.batch_year?`Class of ${g.batch_year}`:'Batch year not set'}</p><p>President: <strong>{g.president_name||'Not assigned yet'}</strong></p><small>{g.member_count} members{g.joined?' · Joined':''}</small><span className="batch-open">View batch →</span></button>)}{!groups.length&&!error&&<p>No batch groups available. Ask the alumni office to create your batch community.</p>}{groups.length>0&&!groups.some(g=>`${g.name} ${g.batch_year||''} ${g.president_name||''}`.toLowerCase().includes(query.toLowerCase()))&&<p>No batches match your search.</p>}</div>:group?<>
   <section className="batch-card batch-overview"><BatchPhoto group={group}/><div><h2>{group.name}</h2><p>{group.batch_year?`Class of ${group.batch_year} · `:''}{group.member_count} members</p><p>Batch president: <strong>{group.president_name||'Not assigned yet'}</strong></p><p>{group.description}</p></div><div className="batch-actions">{!group.joined&&<button disabled={busy} className="batch-primary" onClick={membership}>Join batch</button>}{group.joined&&onOpenChat&&<button className="batch-primary" onClick={()=>onOpenChat(group)}>Open group chat</button>}{group.joined&&<small>You are a member · Chat opens in the chat box</small>}{admin&&manager&&<button onClick={()=>setEditing(v=>!v)}>Edit batch details</button>}</div></section>
   {group.joined||manager?<><section className="batch-support-links" aria-label="Batch contacts"><div><h2>Your batch contact</h2><p>{group.president_name?`${group.president_name} · Batch president`:'A batch president has not been assigned yet.'}</p>{group.joined&&onMessage&&group.president_id&&group.president_id!==user.id&&<button type="button" disabled={busy} onClick={()=>messageMember(group.president_id)}>Message batch president</button>}{group.president_id===user.id&&<p>You are the batch president. Use Announcements to share official batch updates.</p>}</div>{onOpenHelp&&<div><h2>Need help from the school?</h2><p>Ask about alumni records, account concerns, or batch details.</p><button type="button" onClick={onOpenHelp}>Contact alumni office</button></div>}</section><nav className="batch-tabs" aria-label="Batch sections">{[['announcement','Announcements'],['members','Members'],['about','About & rules']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
   {tab==='members'?<section className="batch-card"><h2>Batch members</h2><label>Find a classmate<input type="search" value={memberQuery} onChange={e=>setMemberQuery(e.target.value)} placeholder="Search by name" /></label><p>{visibleMembers.length} members{memberQuery?' matching your search':''}</p><div className="batch-members">{visibleMembers.map(p=><article key={p.id}>{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span className="batch-member-initials">{memberName(p).slice(0,1)}</span>}<div><strong>{memberName(p)}</strong><small>{p.is_president?'Batch president':'Batch member'}</small>{group.joined&&onMessage&&p.id!==user.id&&<button type="button" disabled={busy} onClick={()=>messageMember(p.id)} aria-label={`Message ${memberName(p)}`}>Message</button>}</div></article>)}</div>{!visibleMembers.length&&<p>No classmates found. Try another name.</p>}</section>:tab==='about'?<section className="batch-card"><h2>About this batch</h2><p>{group.description||'The alumni office has not added a description yet.'}</p><h3>Community rules</h3><p className="batch-rules">{group.rules}</p><h3>How to use your batch page</h3><ul><li>Check Announcements for updates from your president and the alumni office.</li><li>Use Members to find classmates and identify your batch president.</li><li>Select Open group chat to ask questions, plan reunions, and help each other in the chat box.</li></ul><h3>Your membership</h3><p>Leaving removes your access to this batch and its chat. Messages you previously shared remain in the conversation.</p>{group.joined&&<button className="batch-leave" disabled={busy} onClick={membership}>Leave batch</button>}</section>:<BatchConversation key={`${group.id}-${tab}`} group={group} user={user} kind="announcement" initialAnnouncementId={group.id===initialGroupId?initialAnnouncementId:null}/>}</>:<p className="batch-card">Join this batch to read announcements, see the member list, and access its conversation in the chat box. Your membership is visible to other batch members.</p>}
  </>:<p>This batch is no longer available.</p>}
  </>}
 </section>;
}
