import { useEffect, useRef, useState } from 'react';
import { supabase } from '../lib/supabase.js';
export function LinkedText({text=''}) { return text.split(/((?:https?:\/\/|www\.)[^\s<>]+)/gi).map((part,i)=> /^(https?:\/\/|www\.)/i.test(part) ? <a key={i} href={/^www\./i.test(part)?`https://${part}`:part} target="_blank" rel="noopener noreferrer">{part}</a>:part); }
export async function mediaUrl(path) { if(!path)return ''; if(/^https:\/\//i.test(path))return path; const {data,error}=await supabase.storage.from('chat-attachments').createSignedUrl(path,3600); if(error)throw error; return data.signedUrl; }
export function useChatSettings(chatKey) {
 const [settings,setSettings]=useState({});
 useEffect(()=>{let active=true; const load=async()=>{if(!chatKey)return;const {data}=await supabase.from('chat_settings').select('*').eq('chat_key',chatKey).maybeSingle();if(active)setSettings(data||{});};setSettings({});load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer);};},[chatKey]);
 return [settings,setSettings];
}

function MenuIcon({name}) {
 const paths={images:'M3 17l5-5 4 4 4-6 5 7 M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2 M8 7h.01',pin:'M9 3h6l-1 6 4 4v2H6v-2l4-4-1-6 M12 15v6',edit:'M14 5l5 5 M4 20l5-1L20 8a2 2 0 0 0-5-5L4 14v6',members:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M17 4a4 4 0 0 1 0 7 M22 21v-2a4 4 0 0 0-3-4',leave:'M9 3H4v18h5 M9 12h12 M17 8l4 4-4 4',block:'M5 5l14 14 M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',close:'M6 6l12 12 M6 18L18 6',back:'M15 5l-7 7 7 7',next:'M9 6l6 6-6 6',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7'};
 return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.images}/></svg>;
}
export function MessageOptions({pinned,busy,onPin,onUnsend}) {
 const root=useRef(null);
 useEffect(()=>{const close=e=>{if(root.current?.open&&(e.type==='keydown'?e.key==='Escape':!root.current.contains(e.target))){root.current.open=false;if(e.type==='keydown')root.current.querySelector('summary').focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',close);};},[]);
 const act=fn=>{root.current.open=false;fn();};
 return <details ref={root} className="batch-message-options" onToggle={e=>{const el=e.currentTarget;if(!el.open)return;document.querySelectorAll('.batch-message-options[open]').forEach(other=>{if(other!==el)other.open=false;});const pop=el.querySelector('.message-options-popover');pop.classList.remove('opens-above');const log=el.closest('.messenger-messages');if(log&&pop.getBoundingClientRect().bottom>log.getBoundingClientRect().bottom-8)pop.classList.add('opens-above');}}><summary aria-label="Message options" title="Message options">{'\u2022\u2022\u2022'}</summary><div className="message-options-popover"><span className="message-options-title">Message options</span><button type="button" disabled={busy} onClick={()=>act(onPin)}><MenuIcon name="pin"/>{pinned?'Unpin message':'Pin message'}</button>{onUnsend&&<button className="option-danger" type="button" disabled={busy} onClick={()=>act(onUnsend)}><MenuIcon name="trash"/>Unsend for everyone</button>}</div></details>;
}

export function ChatMenu({chatKey,group,user,members,settings,onSettings,onLeave,onBlock}) {
 const root=useRef(null),trigger=useRef(null),panel=useRef(null),coverInput=useRef(null);
 const [notice,setNotice]=useState('');
 const [open,setOpen]=useState(false),[tab,setTab]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[nicknames,setNicknames]=useState({});
 function close(){setOpen(false);trigger.current?.focus();}
 useEffect(()=>{if(!open)return;panel.current?.querySelector('button')?.focus();const dismiss=e=>{if(e.type==='keydown'&&e.key==='Escape'){e.stopPropagation();close();}else if(e.type==='pointerdown'&&!root.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',dismiss);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',dismiss);};},[open]);
 async function save(patch){setBusy(true);setError('');try{const {data,error}=await supabase.rpc('update_chat_settings',{p_key:chatKey,p_patch:patch});if(error)throw error;onSettings(data);setTab('');setNotice('Changes saved for this chat.');return true;}catch(e){setError(['42P01','42703','PGRST202','PGRST204','PGRST205'].includes(e.code)?'Chat settings are not available yet. Please contact the alumni office.':e.message);}finally{setBusy(false);}}
 async function show(next){setTab(next);setError('');setNotice('');setRows([]);setName(settings.name||'');setNicknames(settings.nicknames||{});if(!['Images','Pinned messages'].includes(next))return;setBusy(true);try{let query=supabase.from(group?'batch_entries':'direct_messages').select('*').is('unsent_at',null).order('created_at',{ascending:false});if(group)query=query.eq('space_id',group.id).eq('kind','chat');else {const ids=chatKey.split(':');query=query.or(`and(sender_id.eq.${ids[1]},recipient_id.eq.${ids[2]}),and(sender_id.eq.${ids[2]},recipient_id.eq.${ids[1]})`);}if(next==='Images')query=query.in('message_type',['image','gif']);else query=query.eq('pinned',true);let all=[];for(let offset=0;;offset+=100){const {data,error}=await query.range(offset,offset+99);if(error)throw error;all.push(...data);if(data.length<100)break;}setRows(await Promise.all(all.map(async r=>({...r,attachment_url:await mediaUrl(r.attachment_url)}))));}catch(e){setError(['42P01','42703','PGRST202','PGRST204','PGRST205'].includes(e.code)?'Chat settings are not available yet. Please contact the alumni office.':e.message);}finally{setBusy(false);}}
 async function unpin(row){setBusy(true);setError('');try{const {error}=await supabase.rpc('pin_chat_message',{p_key:chatKey,p_message:row.id,p_pinned:false});if(error)throw error;setRows(current=>current.filter(r=>r.id!==row.id));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function cover(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>15*1024*1024){setError('Choose an image up to 15 MB.');return;}setBusy(true);const path=`${user.id}/${crypto.randomUUID()}-cover`;const {error}=await supabase.storage.from('chat-attachments').upload(path,file);if(error){setError(error.message);setBusy(false);return;}if(!await save({cover:path}))await supabase.storage.from('chat-attachments').remove([path]);}
 async function leave(){if(!window.confirm('Leave this group and its batch? You will lose access to its chat.'))return;setBusy(true);const {error}=await supabase.from('alumni_space_members').delete().eq('space_id',group.id).eq('user_id',user.id);setBusy(false);if(error)setError(error.message);else{window.dispatchEvent(new Event('batch-membership-changed'));onLeave?.();}}
 const options=[{tab:'Images',label:'Photos & GIFs',hint:'Browse media shared in this chat',icon:'images'},{tab:'Pinned messages',label:'Pinned messages',hint:'Find messages saved for everyone',icon:'pin'},{tab:'Chat name',label:'Change chat name',hint:'Give this conversation a name',icon:'edit'},{tab:'Nicknames',label:'Member nicknames',hint:'Choose names used in this chat',icon:'members'},{tab:'Cover photo',label:'Change cover photo',hint:'Personalize the top of your chat',icon:'images'}];
 const title=options.find(o=>o.tab===tab)?.label||'Chat options';
 return <div ref={root} className="chat-settings" onClick={e=>e.stopPropagation()}><button ref={trigger} type="button" aria-label="Chat options" title="Chat options" aria-expanded={open} aria-haspopup="dialog" onClick={()=>{setOpen(!open);setTab('');setError('');setNotice('');}}>{'\u2022\u2022\u2022'}</button>{open&&<div ref={panel} className="chat-settings-panel" role="dialog" aria-label={title}>
  <div className="chat-menu-heading">{tab&&<button className="chat-menu-icon" type="button" onClick={()=>{setTab('');setError('');}} aria-label="Back to chat options"><MenuIcon name="back"/></button>}<div><h3>{title}</h3>{!tab&&<p>Manage your conversation</p>}</div><button className="chat-menu-icon" type="button" onClick={close} aria-label="Close chat options"><MenuIcon name="close"/></button></div>
  <div className="chat-menu-content">{!tab?<nav aria-label="Conversation settings">{options.map((o,i)=><div key={o.tab}>{(i===0||i===2)&&<p className="chat-menu-section">{i===0?'Shared in this chat':'Personalize'}</p>}<button className="chat-menu-option" type="button" onClick={()=>show(o.tab)}><span className="chat-menu-option-icon"><MenuIcon name={o.icon}/></span><span><strong>{o.label}</strong><small>{o.hint}</small></span><MenuIcon name="next"/></button></div>)}{(onBlock||group)&&<div className="chat-menu-safety">{onBlock&&<button className="chat-menu-option option-danger" type="button" disabled={busy} onClick={onBlock}><span className="chat-menu-option-icon"><MenuIcon name="block"/></span><span><strong>Block alumnus</strong><small>Stop messages from this person</small></span></button>}{group&&<button className="chat-menu-option option-danger" type="button" disabled={busy} onClick={leave}><span className="chat-menu-option-icon"><MenuIcon name="leave"/></span><span><strong>Leave group chat</strong><small>Also leaves your batch membership</small></span></button>}</div>}</nav>:<>
   {tab==='Chat name'&&<form onSubmit={e=>{e.preventDefault();save({name:name.trim()});}}><p className="chat-menu-help">Everyone in this chat will see this name. Leave it blank to use the original name.</p><label>Chat name<input placeholder={group?.name||'Enter a chat name'} value={name} maxLength={100} disabled={busy} onChange={e=>setName(e.target.value)}/></label><span className="chat-field-count">{name.length}/100</span><button className="chat-menu-save" disabled={busy}>Save name</button></form>}
   {tab==='Nicknames'&&<form onSubmit={e=>{e.preventDefault();save({nicknames:Object.fromEntries(members.map(p=>[p.id,nicknames[p.id]||'']))});}}><p className="chat-menu-help">Nicknames are visible to everyone here. Leave a field blank to use the member's name.</p>{members.map(p=><label className="chat-nickname-member" key={p.id}><span className="chat-nickname-identity"><span className="chat-nickname-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:([p.first_name?.[0],p.last_name?.[0]].filter(Boolean).join('').toUpperCase()||'A')}</span><span>{[p.first_name,p.last_name].filter(Boolean).join(' ')||'Alumni member'}{p.id===user.id&&<small> (You)</small>}</span></span><input placeholder="Add a nickname" maxLength={50} disabled={busy} value={nicknames[p.id]||''} onChange={e=>setNicknames({...nicknames,[p.id]:e.target.value})}/></label>)}<button className="chat-menu-save" disabled={busy}>Save nicknames</button></form>}
   {tab==='Cover photo'&&<div className="chat-cover-editor"><ChatCover path={settings.cover}/><div className="chat-cover-placeholder"><MenuIcon name="images"/><p>Choose a cover for everyone in this chat.</p><small>JPG, PNG, WebP or GIF. Up to 15 MB.</small></div><button className="chat-menu-save" type="button" disabled={busy} onClick={()=>coverInput.current?.click()}>Choose cover photo</button><input ref={coverInput} hidden aria-label="Choose cover photo" type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={cover}/></div>}
   {['Images','Pinned messages'].includes(tab)&&<div className={`chat-saved-media ${tab==='Images'?'chat-photo-grid':''}`}>{rows.map(r=><article key={r.id}>{r.attachment_url&&['image','gif'].includes(r.message_type)&&<a href={r.attachment_url} target="_blank" rel="noopener noreferrer" aria-label="Open shared image in a new tab"><img src={r.attachment_url} alt={r.attachment_name||'Shared image'}/></a>}{tab==='Pinned messages'&&<p><LinkedText text={r.body}/></p>}<small>{new Date(r.created_at).toLocaleDateString()}</small>{tab==='Pinned messages'&&<button type="button" disabled={busy} onClick={()=>unpin(r)}>Unpin message</button>}</article>)}{!busy&&!error&&!rows.length&&<div className="chat-menu-empty"><MenuIcon name={tab==='Images'?'images':'pin'}/><strong>{tab==='Images'?'No photos yet':'No pinned messages yet'}</strong><p>{tab==='Images'?'Photos and GIFs you share will appear here.':'Open the three dots beside a message and choose Pin message.'}</p></div>}</div>}
  </>}{busy&&<p className="chat-menu-feedback" role="status">Please wait...</p>}{notice&&<p className="chat-menu-feedback" role="status">{notice}</p>}{error&&<p className="chat-menu-error" role="alert">{error}</p>}</div></div>}</div>;

}
export function ChatCover({path}){const [url,setUrl]=useState('');useEffect(()=>{let active=true;setUrl('');mediaUrl(path).then(u=>{if(active)setUrl(u);}).catch(()=>{});return()=>{active=false;};},[path]);return url?<img className="chat-cover" src={url} alt="Chat cover"/>:null;}
export function GroupMedia({onSend,disabled,onError}){
 const photoInput=useRef(null);
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[gifs,setGifs]=useState([]),[busy,setBusy]=useState(false);
 async function search(e){e?.preventDefault();setBusy(true);try{const res=await fetch(`/api/gifs?q=${encodeURIComponent(query)}`);const data=await res.json();if(!res.ok)throw new Error(data.meta?.msg||'GIF search unavailable');setGifs(data.gifs||[]);}catch(e){onError(e.message);}finally{setBusy(false);}}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>15*1024*1024)return onError('Choose a photo or GIF up to 15 MB.');setBusy(true);try{await onSend(file);}catch(e){onError(e.message);}finally{setBusy(false);}}
 return <div className="group-media-tools"><button className="group-photo-button" type="button" aria-label="Send photo" title="Send photo" disabled={disabled||busy} onClick={()=>photoInput.current?.click()}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/></svg><span>Photo</span></button><input ref={photoInput} hidden aria-label="Choose photo or GIF" type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={disabled||busy} onChange={upload}/><button type="button" disabled={disabled||busy} onClick={()=>{setOpen(!open);if(!open)search();}}>GIF</button>{open&&<div className="gif-picker"><form onSubmit={search}><input aria-label="Search GIFs" placeholder="Search GIPHY" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy}>Search</button><button type="button" onClick={()=>setOpen(false)}>Close</button></form><div>{gifs.map(g=><button type="button" key={g.id} disabled={disabled||busy} onClick={async()=>{if(await onSend({message_type:'gif',attachment_url:g.images.fixed_height_small.url,body:g.title||'GIF'}))setOpen(false);}}><img src={g.images.fixed_height_small.url} alt={g.title}/></button>)}</div><small>Powered by GIPHY</small></div>}</div>;
}
