import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase.js';
import './Gallery.css';
import './GalleryManagement.css';

const categories=['Campus Memories','Graduation','Reunion','Awards & Recognition','Career Milestone','Entrepreneurship','Community Service','University Event'];
const blank={title:'',description:'',category:'Campus Memories',photoDate:'',batchYear:'',peopleNames:'',ownership:false,consent:false};
const galleryImageTypes=new Set(['image/jpeg','image/png','image/webp']);

export default function Gallery({user,profile,verificationStatus,initialStoryId,onStoryOpened}){
 const[photos,setPhotos]=useState([]),[selectedPhoto,setSelectedPhoto]=useState(null),[loading,setLoading]=useState(true);
 const[submitOpen,setSubmitOpen]=useState(false),[form,setForm]=useState(blank),[file,setFile]=useState(null),[message,setMessage]=useState(''),[submitting,setSubmitting]=useState(false);
 const[mineOpen,setMineOpen]=useState(false),[mine,setMine]=useState([]),[mineLoading,setMineLoading]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState('All stories');
 const[uploadMaxMb,setUploadMaxMb]=useState(10);
 const availableCategories=useMemo(()=>[...new Set(photos.map(p=>p.category).filter(Boolean))].sort(),[photos]);
 const visiblePhotos=useMemo(()=>photos.filter(p=>category==='All stories'||p.category===category).filter(p=>`${p.title||''} ${p.description||''} ${p.author_name||''} ${p.people_names||''}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured))||new Date(b.photo_date||b.created_at)-new Date(a.photo_date||a.created_at)),[photos,query,category]);
 async function load(){setLoading(true);try{const response=await fetch('/api/gallery'),result=await response.json();if(!response.ok)throw new Error(result.error);setPhotos(result.photos||[])}catch(error){setMessage(error.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!initialStoryId||loading)return;const story=photos.find(photo=>photo.id===initialStoryId);if(story)setSelectedPhoto(story);else setMessage('This story is no longer available. Browse the published stories below.');onStoryOpened?.()},[initialStoryId,loading,photos,onStoryOpened]);
 useEffect(()=>{fetch('/api/config').then(response=>response.ok?response.json():null).then(config=>{if(config?.uploadMaxMb)setUploadMaxMb(Math.min(Number(config.uploadMaxMb)||10,10))}).catch(()=>{})},[]);
 async function loadMine(){if(!user?.id)return;setMineLoading(true);const{data,error}=await supabase.from('gallery_submissions').select('id,title,status,reviewer_note,image_path,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)setMessage(error.message);else setMine(data||[]);setMineLoading(false)}
 useEffect(()=>{if(mineOpen)loadMine()},[mineOpen,user?.id]);
 useEffect(()=>{if(!selectedPhoto)return;const close=e=>e.key==='Escape'&&setSelectedPhoto(null);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[selectedPhoto]);
 async function withdraw(item){if(!window.confirm(`Withdraw "${item.title}"?`))return;const{error}=await supabase.from('gallery_submissions').delete().eq('id',item.id).eq('user_id',user.id);if(error)return setMessage(error.message);await supabase.storage.from('gallery-media').remove([item.image_path]);setMine(current=>current.filter(x=>x.id!==item.id));setMessage('Gallery submission withdrawn.')}
 function validateFile(nextFile){if(!nextFile)return'Choose a photo to submit.';if(!galleryImageTypes.has(nextFile.type))return'Choose a JPG, PNG, or WebP image.';if(nextFile.size>uploadMaxMb*1024*1024)return`Photo must be ${uploadMaxMb} MB or smaller.`;return''}
 function chooseFile(nextFile){const error=validateFile(nextFile);setFile(error?null:nextFile);setMessage(error)}
 async function submit(event){event.preventDefault();if(verificationStatus!=='verified')return setMessage('Your alumni account must be verified before submitting photos.');const fileError=validateFile(file);if(fileError)return setMessage(fileError);setSubmitting(true);setMessage('');const path=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error:uploadError}=await supabase.storage.from('gallery-media').upload(path,file,{contentType:file.type,upsert:false});if(uploadError){setMessage(uploadError.message);setSubmitting(false);return}const author=[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||user.email;const{error}=await supabase.from('gallery_submissions').insert({user_id:user.id,author_name:author,title:form.title.trim(),description:form.description.trim(),category:form.category,photo_date:form.photoDate||null,batch_year:form.batchYear?Number(form.batchYear):null,people_names:form.peopleNames.trim()||null,image_path:path,ownership_confirmed:form.ownership,consent_confirmed:form.consent});if(error){await supabase.storage.from('gallery-media').remove([path]);setMessage(error.message)}else{setMessage('Photo submitted for review. Track it in My submissions.');setSubmitOpen(false);setMineOpen(true);setForm(blank);setFile(null)}setSubmitting(false)}
 function openStory(photo){setSelectedPhoto(photo);window.scrollTo({top:0,behavior:'smooth'})}
 if(selectedPhoto)return <article className="gallery-story-page simple"><div className="gallery-story-simple"><button className="gallery-story-back" onClick={()=>{setSelectedPhoto(null);window.scrollTo({top:0,behavior:'smooth'})}}>← Back to Gallery</button><figure><img src={selectedPhoto.url} alt={selectedPhoto.title}/></figure><section><p className="story-page-label">{selectedPhoto.category}</p><h1>{selectedPhoto.title}</h1><p className="gallery-story-byline">Shared by <strong>{selectedPhoto.author_name}</strong> · {new Date(selectedPhoto.photo_date||selectedPhoto.created_at).toLocaleDateString()}{selectedPhoto.batch_year&&` · Class of ${selectedPhoto.batch_year}`}</p><div className="story-page-description">{selectedPhoto.description}</div>{selectedPhoto.people_names&&<p className="gallery-story-people"><strong>People shown:</strong> {selectedPhoto.people_names}</p>}</section></div></article>
 return <section className="gallery-page">
  <header className="gallery-header"><div><p>NDDU Alumni Community</p><h1>Alumni Gallery</h1><span>Celebrate alumni achievements, campus memories, reunions, service, and milestones.</span></div>{user&&<div className="gallery-header-actions"><button onClick={()=>setMineOpen(v=>!v)}>{mineOpen?'Close submissions':'My submissions'}</button><button onClick={()=>setSubmitOpen(true)}>＋ Submit a photo</button></div>}</header>
  {message&&<p className="gallery-message" role="status">{message}</p>}
  {mineOpen&&<section className="gallery-my-submissions"><header><div><p>Submission center</p><h2>My gallery submissions</h2><span>Follow moderation progress and reviewer feedback.</span></div><button onClick={loadMine}>Refresh</button></header>{mineLoading?<p>Loading submissions…</p>:mine.length?<div>{mine.map(item=><article key={item.id}><div><strong>{item.title}</strong><span className={`submission-status ${item.status}`}>{item.status.replaceAll('_',' ')}</span><small>Submitted {new Date(item.created_at).toLocaleDateString()}</small>{item.reviewer_note&&<p><b>Reviewer note:</b> {item.reviewer_note}</p>}</div>{['pending','needs_information'].includes(item.status)&&<button onClick={()=>withdraw(item)}>Withdraw</button>}</article>)}</div>:<div className="gallery-submission-empty"><strong>No submissions yet</strong><span>Your photos and review status will appear here.</span><button onClick={()=>setSubmitOpen(true)}>Submit your first photo</button></div>}</section>}
  <section className="gallery-browser"><div><p>Alumni archive</p><h2>Stories from our community</h2><span>{loading?'Loading gallery…':`${visiblePhotos.length} ${visiblePhotos.length===1?'story':'stories'}`}</span></div><div className="gallery-browser-controls"><label><span>Search stories</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title, alumnus, or keyword"/></label><label><span>Collection</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>All stories</option>{availableCategories.map(item=><option key={item}>{item}</option>)}</select></label>{(query||category!=='All stories')&&<button onClick={()=>{setQuery('');setCategory('All stories')}}>Clear filters</button>}</div></section>
  {loading?<p className="gallery-state">Loading approved photos…</p>:visiblePhotos.length?<div className="gallery-grid">{visiblePhotos.map(photo=><article className={`gallery-card ${photo.featured?'featured':''}`} key={photo.id}><button className="gallery-card-image" onClick={()=>openStory(photo)}><img src={photo.url} alt={photo.title} loading="lazy"/>{photo.featured&&<span>Featured story</span>}</button><div className="gallery-card-copy"><p className="gallery-card-meta"><span>{photo.category}</span><time>{new Date(photo.photo_date||photo.created_at).toLocaleDateString()}</time></p><h2>{photo.title}</h2><p className="gallery-card-description">{photo.description}</p><p className="gallery-card-author">Shared by <strong>{photo.author_name}</strong>{photo.batch_year&&` · Class of ${photo.batch_year}`}</p></div><button className="gallery-card-action" onClick={()=>openStory(photo)}>View story →</button></article>)}</div>:<div className="gallery-state"><h2>No stories found</h2><p>{photos.length?'Try another search or collection.':'Be the first verified alumnus to share a memory or achievement.'}</p>{user&&<button onClick={()=>setSubmitOpen(true)}>Submit a photo</button>}</div>}
  {submitOpen&&<div className="gallery-submit-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSubmitOpen(false)}><form className="gallery-submit" onSubmit={submit}><header><div><small>Alumni gallery</small><h2>Share a story</h2><p>Submissions are reviewed before appearing publicly.</p></div><button type="button" onClick={()=>setSubmitOpen(false)} aria-label="Close">×</button></header>{verificationStatus!=='verified'?<div className="gallery-submit-warning">Your alumni account must be verified before submitting photos.</div>:<><section className="gallery-form-intro"><b>What belongs here?</b><span>Achievements, awards, reunions, graduations, service, entrepreneurship, and meaningful campus memories.</span></section><label className="gallery-file-field">Photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseFile(e.target.files?.[0]||null)} required/><small>{file?`${file.name} selected`:`Use a clear JPG, PNG, or WebP image up to ${uploadMaxMb} MB.`}</small></label><label>Story title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} maxLength="120" placeholder="Example: Alumni receives national teaching award" required/></label><label>Story / description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} minLength="10" maxLength="1500" placeholder="Explain the achievement, memory, people involved, and why it matters." required/><small>{form.description.length} of 1,500 characters</small></label><div><label>Collection<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Date represented<input type="date" max={new Date().toISOString().slice(0,10)} value={form.photoDate} onChange={e=>setForm({...form,photoDate:e.target.value})}/></label></div><div><label>Batch year<input type="number" min="1953" max={new Date().getFullYear()} value={form.batchYear} onChange={e=>setForm({...form,batchYear:e.target.value})} placeholder="Optional"/></label><label>People shown<input value={form.peopleNames} maxLength="500" onChange={e=>setForm({...form,peopleNames:e.target.value})} placeholder="Optional names"/></label></div><fieldset className="gallery-consent"><legend>Permission and consent</legend><label className="gallery-check"><input type="checkbox" checked={form.ownership} onChange={e=>setForm({...form,ownership:e.target.checked})} required/> I own this photo or have permission to submit it.</label><label className="gallery-check"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})} required/> I consent to publication in the NDDU Alumni Gallery.</label></fieldset><footer><button type="button" onClick={()=>setSubmitOpen(false)}>Cancel</button><button disabled={submitting}>{submitting?'Submitting…':'Submit for review'}</button></footer></>}</form></div>}
 </section>
}
