import {useState} from 'react';
const topics=[
 {title:'Account & profile',description:'Get help with your profile, account access or verification.',category:'General assistance',icon:'account'},
 {title:'Alumni records',description:'Ask about incorrect names, batch details or other alumni records.',category:'Record correction',icon:'records'},
 {title:'Documents & requests',description:'Ask the office about documents and the steps to request them.',category:'Document inquiry',icon:'document'},
 {title:'Using the alumni portal',description:'Report a problem with chats, groups, events or another feature.',category:'General assistance',icon:'portal'}
];
const faqs=[
 {q:'How do I update my profile?',a:'Open your account menu and select Profile. You can update your profile there. If an alumni record is incorrect or you cannot change a detail, send a Record correction request to the alumni office.'},
 {q:'How do I join my batch group?',a:'Open Alumni groups, find your batch and choose Join batch. After joining, you can read its announcements and use the group chat. You need a verified alumni account to join.'},
 {q:'How do I report a problem with the portal?',a:'Choose Using the alumni portal below and describe what you were trying to do, what happened and any error message. Include your device or browser if relevant so the office can understand the problem.'},
 {q:'Can I request an official document here?',a:'Choose Documents & requests to ask the alumni office about the process. The office can advise you on the next steps; submitting an inquiry here does not issue an official document.'},
 {q:'Where can I see replies to my request?',a:'Go to My requests on this page and open View conversation. Replies from the alumni office appear there. Use Check for updates to load the latest status and replies.'},
 {q:'What do the request statuses mean?',a:'Submitted means your request has been sent. Being reviewed means the office is reviewing it. Needs information means you should open the conversation and provide the details requested. Completed means the office has marked the request complete.'},
 {q:'Who can read my support request?',a:'Your request and its replies are visible to you and authorized administrators. Do not share your password or payment details in a request.'}
];
function SupportIcon({name}){const paths={account:'M20 21v-2a6 6 0 0 0-6-6h-4a6 6 0 0 0-6 6v2 M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',records:'M4 3h16v18H4z M8 8h8 M8 12h8 M8 16h5',document:'M14 2H5v20h14V7l-5-5v5h5 M8 12h8 M8 16h6',portal:'M3 4h18v14H3z M8 22h8 M12 18v4',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6'};return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;}
export default function HelpCenter({onRequest,onRequests}){
 const [query,setQuery]=useState('');
 const matches=faqs.filter(f=>`${f.q} ${f.a}`.toLowerCase().includes(query.trim().toLowerCase()));
 return <><header className="support-hero"><div><span className="support-eyebrow">NDDU ALUMNI HELP CENTER</span><h1>How can we help you?</h1><p>Find an answer, get help from the alumni office, or follow up on a request.</p><label className="support-search"><SupportIcon name="search"/><input aria-label="Search help articles" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search help: profile, documents, group chat..."/></label></div><button type="button" onClick={onRequests}>View my requests <span aria-hidden="true">&#8599;</span></button></header>
 <section className="support-topics" aria-labelledby="support-topics-title"><div className="support-section-title"><h2 id="support-topics-title">What do you need help with?</h2><p>Choose a topic to contact the alumni office.</p></div><div className="support-topic-grid">{topics.map(t=><button type="button" key={t.title} className="support-topic" onClick={()=>onRequest(t.category,t.title)}><span className="support-topic-icon"><SupportIcon name={t.icon}/></span><strong>{t.title}</strong><span>{t.description}</span><b>Get help <span aria-hidden="true">&#8594;</span></b></button>)}</div></section>
 <div className="support-answer-layout"><section className="support-faq" aria-labelledby="support-faq-title"><div className="support-section-title"><h2 id="support-faq-title">{query.trim()?'Search results':'Frequently asked questions'}</h2><p>{query.trim()?`${matches.length} matching answers`:'Quick answers to common questions about the portal.'}</p></div><div className="support-faq-list">{matches.map(f=><details key={f.q}><summary>{f.q}<span aria-hidden="true">+</span></summary><p>{f.a}</p></details>)}{!matches.length&&<div className="support-no-results"><strong>No answers found</strong><p>Try a different keyword or send the alumni office a request.</p><button type="button" onClick={()=>setQuery('')}>Clear search</button></div>}</div></section><aside className="support-contact"><span className="support-topic-icon"><SupportIcon name="account"/></span><h2>Still need help?</h2><p>Send a private request to the alumni office. You can read replies and add more details in My requests.</p><button type="button" className="cs-primary" onClick={()=>onRequest('General assistance')}>Contact alumni office</button><small>Your conversation stays with your request so you can follow up in one place.</small></aside></div></>;
}
