import {useState} from 'react';
const topics=[
 {title:'Account & profile',description:'Get help with your profile, account access or verification.',category:'General assistance',icon:'account'},
 {title:'Alumni records',description:'Ask about incorrect names, batch details or other alumni records.',category:'Record correction',icon:'records'},
 {title:'Documents & requests',description:'Ask the office about documents and the steps to request them.',category:'Document inquiry',icon:'document'},
 {title:'Using the alumni portal',description:'Report a problem with chats, groups, events or another feature.',category:'General assistance',icon:'portal'}
];
export const faqs=[
 {q:'How do I update my profile?',a:'Open the account menu and select the My alumni account card that shows your name and email. On your Profile page, select Edit profile, update the fields shown in the Edit alumni profile form, then select Save changes at the bottom. A Profile saved successfully message confirms the update. If an alumni record is incorrect or a field is locked, contact the alumni office with a Record correction request.'},
 {q:'How do I change my name, email, photo, or other profile details?',a:'Open the account menu and select the My alumni account card that shows your name and email, then select Edit profile on your Profile page. Update the fields shown and select Save changes. To change your profile picture, use the Profile picture section and Choose picture. Select a JPG, PNG, or WebP image no larger than 2 MB, check its preview, then save. Email is not an editable field in this profile form. For an email change or incorrect locked alumni record, send the alumni office a General assistance or Record correction request.'},
 {q:'I forgot my password or cannot sign in. What should I do?',a:'Use the Forgot password link on the sign-in screen and follow the instructions sent to your account email. Check your spam folder too. If you no longer have access to that email or the reset link fails, contact the alumni office through a General assistance request. Never send your password.'},
 {q:'How do I create an account?',a:'On Welcome back, select Create an account. Fill in First Name, Last Name, Email, Password, and Confirm Password. For an alumni account, keep Alumni selected and complete Education Information: Department / College, Course / Program, and Graduation Year; Degree fills automatically and Batch Name is optional. Accept the Terms of Service and Privacy Policy, complete the security check if shown, then select Create Alumni Account. Check your email to confirm. Your alumni profile will be pending verification.'},
 {q:'How do I verify my alumni account?',a:'Open the account menu and select Verify alumni status. In the Alumni verification form, enter Name used while studying, Graduation date (DD/MM/YYYY), Batch name, and Course or program. Attach a degree certificate, transcript, or official alumni record as PDF, JPG, or PNG up to 10 MB, then select Submit for verification. The status changes to Under review while the alumni office reviews it. Do not upload a government or personal ID.'},
 {q:'Why is my alumni verification pending or rejected?',a:'The alumni office may still be reviewing your submission or may need more information. Check your account verification status and any request replies. If you do not see an explanation, contact the alumni office with your name and batch year; do not include passwords or sensitive identity documents in chat.'},
 {q:'How do I join my batch group?',a:'If you have already joined your batch, select the green chat button and open your batch under Your batch chats. If it is not listed, open Menu on a phone and choose Directory, or choose Directory from the site navigation on a computer. On Alumni directory, select Browse batch groups under “Looking for your batch?”, search by batch name, year, or president, open the matching card with View batch, then select Join batch. You need a verified alumni account. After joining, the batch appears under Your batch chats; select it there to open the group conversation.'},
 {q:'How do I send a direct message to another alumnus?',a:'Open the green chat button, search for the alumnus under Direct messages, and select their name. Type your message in the conversation box and select Send. You can return to the conversation from the Chats panel.'},
 {q:'I cannot find my batch or join a group. How can I get access?',a:'Open Directory and select Browse batch groups in the “Looking for your batch?” panel. On Alumni batch groups, use Find a batch and search by batch name, year, or president. Open the matching card and select Join batch. Joining requires a verified alumni account. If your batch is missing or the Join batch action fails, send a Record correction request for incorrect batch details or a General assistance request for a technical problem.'},
 {q:'How do I leave a batch group?',a:'Choose Directory in the site navigation, then select Browse batch groups in the “Looking for your batch?” panel. Open your batch card marked Joined, select About & rules, and scroll to Your membership. Select Leave batch, then confirm the browser message. Leaving also removes your access to that batch’s group chat.'},
 {q:'Why can’t I see chats or send a message?',a:'Confirm that you are signed in, then reopen the chat panel and check your connection. Batch chat requires joining the batch; some community features require a verified account. If the problem continues, report what happened and any error message through a General assistance request.'},
 {q:'How do I report inappropriate messages or block someone?',a:'Open the conversation options to review the available chat controls, including blocking where available. For harassment or a safety concern, contact the alumni office through a private General assistance request and include relevant details. Do not post private information publicly.'},
 {q:'How do I report a problem with the portal?',a:'Choose Using the alumni portal below and describe what you were trying to do, what happened and any error message. Include your device or browser if relevant so the office can understand the problem.'},
 {q:'The portal is not loading or showing an error. What can I try?',a:'Refresh the page and check your internet connection. If the issue remains, note the page, action, error message, and browser or device, then send a General assistance request to the alumni office.'},
 {q:'Can I request an official document here?',a:'Choose Documents & requests to ask the alumni office about the process. The office can advise you on the next steps; submitting an inquiry here does not issue an official document.'},
 {q:'How do I ask for a certificate, transcript, or other alumni document?',a:'Open Help & support and choose Documents & requests, then describe the document you need and ask about the process. The office will advise you on next steps. The portal inquiry itself does not issue a document.'},
 {q:'How do I submit a support request?',a:'Open Help & support, choose the topic closest to your question, and complete the request form with a short subject and clear details. Your request is private to you and authorized administrators. Do not include passwords or payment details.'},
 {q:'How do I check a request or reply to the alumni office?',a:'Open Help & support and find My requests. Select View conversation on the request to read replies or send more details. Select Check for updates to load the latest status and replies.'},
 {q:'Can I add details after I submit a request?',a:'Open My requests in Help & support, select View conversation for your request, and add a reply with the additional information.'},
 {q:'Where can I see replies to my request?',a:'Go to My requests on this page and open View conversation. Replies from the alumni office appear there. Use Check for updates to load the latest status and replies.'},
 {q:'What do the request statuses mean?',a:'Submitted means your request has been sent. Being reviewed means the office is reviewing it. Needs information means you should open the conversation and provide the details requested. Completed means the office has marked the request complete.'},
 {q:'Who can read my support request?',a:'Your request and its replies are visible to you and authorized administrators. Do not share your password or payment details in a request.'},
 {q:'How do I contact the alumni office?',a:'Open Help & support and choose Contact alumni office or select a topic such as Account & profile, Alumni records, Documents & requests, or Using the alumni portal. This creates a private request you can follow in My requests.'},
 {q:'How do I update my profile picture?',a:'Open the account menu and select the My alumni account card that shows your name and email. On your Profile page, select Edit profile. Under Profile picture, select Choose picture. Your device’s file picker opens; choose a JPG, PNG, or WebP image no larger than 2 MB. Check the preview, then select Save changes at the bottom. You should see a Profile saved successfully message. If the picture will not save, contact the alumni office with a General assistance request.'},
 {q:'Can I use the portal on my phone?',a:'Yes. Open the alumni portal in your phone’s web browser. Select Menu to open the site navigation; choose Directory to find alumni and batch groups. Open Chats with the green chat button in the lower-right corner. To reach Help & support, select Account or your name in the page header, then choose Help & support. If a control is difficult to use, include your phone model and browser in a General assistance request.'}
];
function SupportIcon({name}){const paths={account:'M20 21v-2a6 6 0 0 0-6-6h-4a6 6 0 0 0-6 6v2 M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',records:'M4 3h16v18H4z M8 8h8 M8 12h8 M8 16h5',document:'M14 2H5v20h14V7l-5-5v5h5 M8 12h8 M8 16h6',portal:'M3 4h18v14H3z M8 22h8 M12 18v4',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6'};return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;}
export default function HelpCenter({onRequest,onRequests}){
 const [query,setQuery]=useState('');
 const matches=faqs.filter(f=>`${f.q} ${f.a}`.toLowerCase().includes(query.trim().toLowerCase()));
 return <><header className="support-hero"><div><span className="support-eyebrow">NDDU ALUMNI HELP CENTER</span><h1>How can we help you?</h1><p>Find an answer, get help from the alumni office, or follow up on a request.</p><label className="support-search"><SupportIcon name="search"/><input aria-label="Search help articles" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search help: profile, documents, group chat..."/></label></div><button type="button" onClick={onRequests}>View my requests <span aria-hidden="true">&#8599;</span></button></header>
 <section className="support-topics" aria-labelledby="support-topics-title"><div className="support-section-title"><h2 id="support-topics-title">What do you need help with?</h2><p>Choose a topic to contact the alumni office.</p></div><div className="support-topic-grid">{topics.map(t=><button type="button" key={t.title} className="support-topic" onClick={()=>onRequest(t.category,t.title)}><span className="support-topic-icon"><SupportIcon name={t.icon}/></span><strong>{t.title}</strong><span>{t.description}</span><b>Get help <span aria-hidden="true">&#8594;</span></b></button>)}</div></section>
 <div className="support-answer-layout"><section className="support-faq" aria-labelledby="support-faq-title"><div className="support-section-title"><h2 id="support-faq-title">{query.trim()?'Search results':'Frequently asked questions'}</h2><p>{query.trim()?`${matches.length} matching answers`:'Quick answers to common questions about the portal.'}</p></div><div className="support-faq-list">{matches.map(f=><details key={f.q}><summary>{f.q}<span aria-hidden="true">+</span></summary><p>{f.a}</p></details>)}{!matches.length&&<div className="support-no-results"><strong>No answers found</strong><p>Try a different keyword or send the alumni office a request.</p><button type="button" onClick={()=>setQuery('')}>Clear search</button></div>}</div></section><aside className="support-contact"><span className="support-topic-icon"><SupportIcon name="account"/></span><h2>Still need help?</h2><p>Send a private request to the alumni office. You can read replies and add more details in My requests.</p><button type="button" className="cs-primary" onClick={()=>onRequest('General assistance')}>Contact alumni office</button><small>Your conversation stays with your request so you can follow up in one place.</small></aside></div></>;
}
